jamSession/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import ListThreads, CreateThread, ThreadView, CreateMessage, CreateThreadFormless
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('', views.AccountList.as_view(), name="all"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('endorse/<int:pk>', views.AddEndorsement.as_view(), name="endorse"),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), 
        name='password_reset'),

    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), 
        name='password-reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), 
        name='password_reset_complete'),

    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),
    path('inbox/create-thread-formless/<int:pk>/', CreateThreadFormless.as_view(), name='create-thread-formless'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),

    
]

jamSession/accounts/templates/accounts/create_thread.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 p-5">
			<a href="{% url 'accounts:inbox' %}" class="btn btn-light">Back to Your Inbox</a>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Start a Conversation!</h3>
		</div>
	</div>


		<div class="col-md-5 col-sm-12">
			<form method="POST">
				{% csrf_token %}
				<p>Enter the username for the person you would like to talk to.</p>
				{{ form | crispy }}
				<div class="d-grid gap-2">
					<button class="custom-btn btn-3 mt-3" type="submit">Continue</button>
				</div>
			</form>
		</div>


</div>

{% endblock content %}

jamSession/accounts/templates/accounts/inbox.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Your Conversations</h3>
		</div>
	</div>



	{% for thread in threads.all %}
	<div class="row mb-3">

			
			<a class="list-group-item list-group-item-action flex-column align-items-start" href="{% url 'accounts:thread' thread.pk %}">
				<div class='row'>
				<div class='col-4'>
				<img class="rounded-circle account-img" src="{{ thread.receiver.profile.avatar.url }}" height ="100" width="100">
				</div>
				<div class='col-4 pt-4'>
				{% if user == thread.user %}
				<h2>@{{ thread.receiver }}</h2>
				{% else %}
				<h2>@{{ thread.user }}</h2>
				{% endif %}
				</div>
				</div>
			</a>

	</div>
	{% endfor %}

	<div class="row">
		<div class="col-md-12 p-5">
			<form method="GET" action="{% url 'accounts:create-thread' %}">
				<button class="custom-btn btn-3" type="submit"><span>New message</span></button>
			</form>
		</div>
	</div>
</div>

{%endblock content %}

jamSession/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="container">
    <h1>Login</h1>
    <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Login</button>
        <small class="text-muted ml-2">
            <a href="{% url 'password_reset' %}">Forgot Password? </a>
        </small>
    {% endbuttons %}
    </form>
</div>

{% endblock %}

jamSession/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="container">
    <h1>Reset Password</h1>
    <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Request Password Reset</button>
    {% endbuttons %}
    </form>
</div>

{% endblock %}

jamSession/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <div class='alert alert-info'>
        Password has been successfully updated
    </div>

    <a href="{% url 'login' %}">Sign In</a>

{% endblock %}

jamSession/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="container">
    <h1>Reset Password</h1>
    <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Reset Password</button>
    {% endbuttons %}
    </form>
</div>

{% endblock %}

jamSession/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

    <div class='alert alert-info'>
        An email has been sent with instructions to reset your password
    </div>

{% endblock %}

jamSession/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div class="content-section pt-2">

  <div class='row'>
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }}" height="200" width="200">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
</div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}


            <div class="form-group col-4 pl-4">
              {{ form.avatar|as_crispy_field }}
            </div> 

        </div>
        <hr/>

          <div class="form-row">
            <div class="form-group col-6">
              {{ form.instruments|as_crispy_field }}
              <div class='pt-4'>
              {{ form.singer|as_crispy_field }}
              </div>
              <div class='pt-4'>
              {{ form.music_production_experience|as_crispy_field }}
              </div>
              <div class='pt-3'>
              {{ form.experience_level|as_crispy_field }}
              </div>
              <div class='pt-3'>
              {{ form.location_zip|as_crispy_field }}
              </div>
              <div class='pt-3'>
              {{ form.profile_text|as_crispy_field }}
              </div>
            </div>
            
          

            <div class="form-group col-6">
              {{ form.goals|as_crispy_field }}
              {{ form.location|as_crispy_field }}
              {{ form.associated_acts|as_crispy_field }}
            </div>

          </div>
          <div class="row">
          <button type="submit" class="custom-btn btn-3"><span>Update</span></button>
          </div>
      </form>
    </div>

{% endblock content %}

jamSession/accounts/templates/accounts/profile_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preprofile %}{% endblock %}
    {% block profile_content %}{% endblock %}
    {% block postprofile %}{% endblock %}
  </div>
</div>

{% endblock %}

jamSession/accounts/templates/accounts/profile_list.html
{% extends 'accounts/profile_base.html' %}
{% load crispy_forms_tags %}
{% block preprofile %}

<div class="col-md-4 pt-2">
	<div class="content">
        <div class="card card-body">
			<h2>Musician Profiles</h2>

			<p>Welcome to the Profiles Page!</p>
            <p>Select a Profile with a shared interest!</p>
        </div>
        <br></br>
            
            <div class="card card-body">
                <h2>Musician Search</h2>
                <form method="get">
                    {{filter.form|crispy}}
                    <p>(location searches surrounding area)</p>
                    <button class='custom-btn btn-3' type='submit'><span>Search</span></button>
                </form>
            </div>
	</div>
</div>


{% endblock %}

{% block profile_content %}

<div class="col-md-8  overflow-hidden pt-2">
	<div class="list-group">
        {% for profile in filter.qs %}
        <a href="{% url 'posts:for_user' username=profile.user.username %}" class="list-group-item list-group-item-action flex-column align-items-start">@{{profile.user.username }}
        <div class='row'>
            <div class='col-4'>
                
                <img class="rounded-circle account-img" src="{{ profile.avatar.url }}" height ="100" width="100">
            </div>

            <div class='col-5'>
            <p class="mb-1">Instrument: {{ profile.instruments }}</p>
            <p class="mb-1">Experience Level: {{ profile.experience_level }}</p>
            <p class="mb-1">Travel Specifications: {{ profile.location }}</p>
            <p class="mb-1">Location: {{ profile.location_zip }}</p>
            </div>
        </div>
        
        </a >

        {% endfor %}
    </div>
</div>

{% endblock %}

jamSession/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="container">
    <h1>Sign Up</h1>
    <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    {% endbuttons %}
    </form>
</div>


{% endblock %}

jamSession/accounts/templates/accounts/thread.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="card col-md-12 mt-5 p-3 shadow-sm">
			{% if thread.receiver == request.user %}
				<h5>@{{ thread.user }}</h5>
			{% else %}
				<h5>@{{ thread.receiver }}</h5>
			{% endif %}
		</div>
	</div>

	{% if message_list.all.count == 0 %}
	<div class="row my-5">
		<div class="col-md-12">
			<p class="empty-text">No Messages</p>
		</div>
	</div>
	{% endif %}

	{% for message in message_list %}
	<div class="row">
		<div class="col-md-12 my-1">
			{% if message.sender_user == request.user %}
				<div class="sent-message my-3">
					<p>{{ message.body }}</p>
				</div>
			{% elif message.receiver_user == request.user %}
				<div class="received-message my-3">
					<p>{{ message.body }}</p>
				</div>
			{% endif %}
		</div>
	</div>
	{% endfor %}

	<div class="row">
		<div class="card col-md-12 p-3 shadow-sm">
			<form method="POST" action="{% url 'accounts:create-message' thread.pk %}" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form | crispy }}

				<div class="d-grid gap-2 mt-3">
					<button class="custom-btn btn-3" type="submit"><span>Send Message</span></button>
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock content %}