jamSession/posts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path('like/<int:pk>', views.AddLike.as_view(), name='like_post'),
]

jamSession/posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

# pip install misaka
import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

#------------------------------------------------------------------------------------------
#                               ** Post Model **
# This model stores all the information for a post including the user, when it was created,
# the message of the post, the group the post belongs to, and the number of likes it has
#------------------------------------------------------------------------------------------
class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="group_post")

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

jamSession/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import Http404, HttpResponseRedirect
from django.views import generic, View
from .models import Post
from django.shortcuts import get_object_or_404

# pip install django-braces
from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

#------------------------------------------------------------------------------------------
#                               ** Add Like View **
# This view is used when the user presses the like button. It determines if the user has 
# already liked a post and adds/removes their like depending on the current status.
# It also determines which page the like was clicked on and returns a redirect to that
# previous page
#------------------------------------------------------------------------------------------
class AddLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_like = False
        
        # check if the user has already liked post
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        # If not, add likes
        if not is_like:
            post.likes.add(request.user)
        # If so, remove like
        if is_like:
            post.likes.remove(request.user)

        next = request.POST.get('next', str(request.META['HTTP_REFERER']))
        return HttpResponseRedirect(next)


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)



class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

jamSession/posts/templates/posts/_post.html
<head>
	{% load static %}
</head>

<div class="media">
	<div class="card card-with-shadow" style="width: 40rem;">
	<h3 class="mr-5 pt-2 pl-2"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h3>

	<div class="card-body">
		<strong>{{ post.user.username }}</strong>
		<h5>{{ post.message_html|safe }}</h5>
			<time class="time">{{ post.created_at }}</time>
			{% if post.group %}
			<span class="group-name">in <a href="{% url 'groups:single' slug=post.group.slug%}">{{ post.group.name }}</a></span>
			<form class='pt-2' action="{% url 'posts:like_post' post.id %}" method="POST">
				{% csrf_token %}
				<button style="background-color: transparent; border; none; box-shadow: none" type="submit", name="post_id" value="{{ post.id }}", class="btn btn-primary btn-sm">
					<img src="/media/upvote.png" alt="My image" height ="20" width="20"></img> 
					
				</button>
			</form>
			<p> Number of likes:{{post.likes.count}}</p>
			{% endif %}
		</h5>
	</div>

		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

jamSession/posts/templates/posts/post_base.html
{% extends "base.html" %}


{% block content %}
<div class="posts-page">
	<div class="container">
		{% block prepost %}{% endblock %}
		{% block post_content %}{% endblock %}
		{% block post_post %}{% endblock %}
	</div>
</div>
{% endblock %}

jamSession/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

jamSession/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<!-- <div class="col-md-8"> -->
    {% include "posts/_post.html" %}
    <br></br>
    
    </form>
<!-- </div> -->
{% endblock %}

jamSession/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap4 %}

{% block post_content %}
<h4>Create New Post</h4>
<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
		<button type="submit" class="custom-btn btn-3 btn-large"><span>Post</span></button>
	{% endbuttons %}
</form>
{% endblock %}

jamSession/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

{% block pre_post_content %}

<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">

				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %} #}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>

		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

jamSession/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="row pt-3">
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<img class="rounded-circle account-img" src="{{ post_user.profile.avatar.url }}" height ="200" width="200">

	<div class='row pt-3'>
	<form class='pr-2'action="{% url 'accounts:endorse' pk=post_user.profile.id %}" method="POST">
		{% csrf_token %}
		<button type="submit",  value="{{ post_user.profile.endorsements.count }}", class="custom-btn btn-3"><span>Endorse User</span></button>
	</form>
	

	<form action="{% url 'accounts:create-thread-formless' post_user.id %}" method='POST'>
		{% csrf_token %}
		<button type="submit", class="custom-btn btn-3"><span>Send Message</span></button>
	</form>
	</div>
	<p class="pt-2"> Number of Endorsements:{{post_user.profile.endorsements.count}}</p>
	<div class="row">
		
	</div>
</div>
<div class="col-md-4 border rounded">
	
	<p>Instrument: {{post_user.profile.instruments}}</p>
	{% if post_user.profile.singer == False %}
	<p>Singer? : No</p>
	{% else %}
	<p>Singer? : Yes</p>
	{% endif %}
	{% if post_user.profile.music_production_experience == False %}
	<p>Music Production Experience? : No</p>
	{% else %}
	<p>Music Production Experience? : Yes</p>
	{% endif %}
	<p>Experience_level: {{post_user.profile.experience_level}}
	<p>Willingness to Travel: {{post_user.profile.location}}</p>
	<p>Zip code: {{post_user.profile.location_zip}}</p>
	<p>Goals: {{post_user.profile.goals}}</p>
	<p>Associated Acts: {{post_user.profile.associated_acts}}</p>
	<p>Bio: {{post_user.profile.profile_text}}</p>

	



		
</div>
</div>

<hr/>
<p>Post History</p>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}