jamSession/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import ListThreads, CreateThread, ThreadView, CreateMessage, CreateThreadFormless
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('', views.AccountList.as_view(), name="all"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
    path('endorse/<int:pk>', views.AddEndorsement.as_view(), name="endorse"),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), 
        name='password_reset'),

    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), 
        name='password-reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), 
        name='password_reset_complete'),

    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),
    path('inbox/create-thread-formless/<int:pk>/', CreateThreadFormless.as_view(), name='create-thread-formless'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),

    
]

jamSession/jamSession/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/',include("groups.urls", namespace="groups")),
    path('posts/', include("posts.urls", namespace="posts")),

    path('password-reset/', 
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), 
        name='password_reset'),

    path('password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), 
        name='password-reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), 
        name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jamSession/posts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path('like/<int:pk>', views.AddLike.as_view(), name='like_post'),
]

jamSession/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'jamSession/css/master.css'%}">



</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mynav" role="navigation" id="navbar">
        <div class="container">
            
                {% if user.is_authenticated %}
                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav align-items-left">
                    <a class ="navbar-brand mynav" href="{% url 'posts:all' %}">Jam Session</a>
                </div>
                <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="{% url 'accounts:all' %}">Browse Musicians</a>
                <a class="nav-item nav-link" href="{% url 'groups:all-gigs' %}">Gigs</a>
                <a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a>
                <a class="nav-item nav-link" href="{% url 'posts:create' %}">Post</a>
                <a class="nav-item nav-link" href="{% url 'accounts:profile' %}">My Account</a>
                <div class="nav-item inbox-icon-container">
                    <a class="nav-item nav-link" href="{% url 'accounts:inbox' %}" class="inbox-icon"><img src="/media/inbox.png" height ="30" width="30"></img></a>
                </div>
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}"> Log Out</a>
                </div>
                </div>
        </div>

                {% else %}

                <div class="navbar-nav align-items-center">
                    <a class ="navbar-brand mynav" href="{% url 'home' %}">Jam Session</a>
                </div>
                <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Log In</a>
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                </div>

                {% endif %}
        </div>
    </nav>

    <div class="container mycontent">
        {% block content %}

        {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

jamSession/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class='text-center'>Welcome to Jam Session!</h1>
        <br></br>
        <h4 class='text-center'>Jam Session is a full-stack application representing a minimum viable product (MVP) of a LinkedIn type social media hub for musicians to find each other, and find people to JAM with and for finding musicians and artists via social media-like functionality.</h4>
    </div>
{% endblock %}

jamSession/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
{% comment %} 
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>
{% endcomment %}

</div>

{% endblock %}

jamSession/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}